sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: lff654321
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wxd12428690ea190c6
    secret: 5edfd97c5bc44283e04ead46fc2fe472

